# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_demo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpc_demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_demo.proto\x12\tgrpc_demo\"\x15\n\x06String\x12\x0b\n\x03str\x18\x01 \x01(\t2\x83\x01\n\x08GrpcDemo\x12\x36\n\x0cgenerate_seq\x12\x11.grpc_demo.String\x1a\x11.grpc_demo.String\"\x00\x12?\n\x13generate_seq_stream\x12\x11.grpc_demo.String\x1a\x11.grpc_demo.String\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRING']._serialized_start=30
  _globals['_STRING']._serialized_end=51
  _globals['_GRPCDEMO']._serialized_start=54
  _globals['_GRPCDEMO']._serialized_end=185
# @@protoc_insertion_point(module_scope)
